In [1]:
import pandas as pd
import numpy as np
housing = pd.read_csv("data.csv")

In [2]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284341   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.705587   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [3]:
%matplotlib inline

In [4]:
import matplotlib.pyplot as plt

In [5]:
# housing.hist(bins=50, figsize=(20,20))

In [6]:
from sklearn.model_selection import train_test_split,StratifiedShuffleSplit
# train , test = train_test_split(housing, test_size=0.2,random_state=42)
# print("train: {}\ntest: {}".format(len(train),len(test)))

In [7]:
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2 ,random_state=42)
for train, test in split.split(housing, housing['CHAS']):
    tr_set = housing.loc[train]
    ts_set = housing.loc[test]

In [8]:
tr_set['CHAS'].value_counts()


0    376
1     28
Name: CHAS, dtype: int64

In [9]:
len(tr_set),len(ts_set)

(404, 102)

In [10]:
housing =tr_set.copy()

In [11]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  399.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.279481   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.716784   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.876500   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.209000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630500   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  404.000000  404.000000  
mean    12.791609   22.509406  
std      7.235740    9.385531  
min      1.730000    5.000000  
25%      6.847500   16.600000  
50%     11.570000   21.150000  
75%     17.102500   25.000000  
max     36.980000   50.000000

## Correlation


In [12]:
corr_matrix = housing.corr()

In [13]:
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.680857
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [1]:
from pandas.plotting import scatter_matrix
attribute = ['MEDV','RM','ZN','LSTAT']
# scatter_matrix(housing[attribute],figsize=(12,10),alpha=0.8)

In [15]:
# housing.plot(kind='scatter', x='RM',y='MEDV') 

In [16]:
housing = tr_set.drop("MEDV", axis=1)
housing_labels = tr_set["MEDV"].copy()

In [17]:
median = housing['RM'].median()
housing['RM'].fillna(median)


254    6.108
348    6.635
476    6.484
321    6.376
326    6.312
       ...  
155    6.152
423    6.103
98     7.820
455    6.525
216    5.888
Name: RM, Length: 404, dtype: float64

In [18]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 404 entries, 254 to 216
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     404 non-null    float64
 1   ZN       404 non-null    float64
 2   INDUS    404 non-null    float64
 3   CHAS     404 non-null    int64  
 4   NOX      404 non-null    float64
 5   RM       399 non-null    float64
 6   AGE      404 non-null    float64
 7   DIS      404 non-null    float64
 8   RAD      404 non-null    int64  
 9   TAX      404 non-null    int64  
 10  PTRATIO  404 non-null    float64
 11  B        404 non-null    float64
 12  LSTAT    404 non-null    float64
dtypes: float64(10), int64(3)
memory usage: 44.2 KB


In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
imputer.fit(housing)

SimpleImputer(strategy='median')

In [20]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.20900e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [21]:
X = imputer.transform(housing)


In [22]:
housing_tr = pd.DataFrame(X, columns=housing.columns)

In [23]:
housing_tr

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
0    0.04819  80.0   3.64   0.0  0.392  6.108  32.0  9.2203   1.0  315.0   
1    0.01501  80.0   2.01   0.0  0.435  6.635  29.7  8.3440   4.0  280.0   
2    4.87141   0.0  18.10   0.0  0.614  6.484  93.6  2.3053  24.0  666.0   
3    0.18159   0.0   7.38   0.0  0.493  6.376  54.3  4.5404   5.0  287.0   
4    0.30347   0.0   7.38   0.0  0.493  6.312  28.9  5.4159   5.0  287.0   
..       ...   ...    ...   ...    ...    ...   ...     ...   ...    ...   
399  3.53501   0.0  19.58   1.0  0.871  6.152  82.6  1.7455   5.0  403.0   
400  7.05042   0.0  18.10   0.0  0.614  6.103  85.1  2.0218  24.0  666.0   
401  0.08187   0.0   2.89   0.0  0.445  7.820  36.9  3.4952   2.0  276.0   
402  4.75237   0.0  18.10   0.0  0.713  6.525  86.5  2.4358  24.0  666.0   
403  0.04560   0.0  13.89   1.0  0.550  5.888  56.0  3.1121   5.0  276.0   

     PTRATIO       B  LSTAT  
0       16.4  392.89   6.57  
1       17.0  390.94   5.99  
2       20.2  396.21  18.68  
3       19.6  396.90   6.87  
4       19.6  396.90   6.15  
..       ...     ...    ...  
399     14.7   88.01  15.02  
400     20.2    2.52  23.29  
401     18.0  393.53   3.57  
402     20.2   50.92  18.13  
403     16.4  392.80  13.51  

[404 rows x 13 columns]

In [24]:
housing = housing_tr.copy()

In [25]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     404 non-null    float64
 1   ZN       404 non-null    float64
 2   INDUS    404 non-null    float64
 3   CHAS     404 non-null    float64
 4   NOX      404 non-null    float64
 5   RM       404 non-null    float64
 6   AGE      404 non-null    float64
 7   DIS      404 non-null    float64
 8   RAD      404 non-null    float64
 9   TAX      404 non-null    float64
 10  PTRATIO  404 non-null    float64
 11  B        404 non-null    float64
 12  LSTAT    404 non-null    float64
dtypes: float64(13)
memory usage: 41.2 KB


In [26]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    #     ..... add as many as you want in your pipeline
    ('std_scaler', StandardScaler()),
])

In [27]:
housing_num = my_pipeline.fit_transform(housing)

In [28]:
housing_num.shape

(404, 13)

In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
# model = LinearRegression()
# model = DecisionTreeRegressor()
model = RandomForestRegressor()
model.fit(housing_num, housing_labels)

RandomForestRegressor()

In [30]:
some_data = housing.iloc[:9]
some_labels = housing_labels.iloc[:9]
# prepared_data = my_pipeline.transform(some_data)
# model.predict(prepared_data)
model.predict(some_data)

array([21.85 , 21.989, 22.198, 21.998, 22.193, 22.198, 21.995, 22.035,
       22.053])

In [31]:
np.array(some_labels)

array([21.9, 24.5, 16.7, 23.1, 23. , 17.2, 24.4, 27.5,  9.5])

In [32]:
from sklearn.metrics import mean_squared_error
housing_predictions = model.predict(housing_num)
mse = mean_squared_error(housing_labels, housing_predictions)
rmse = np.sqrt(mse)

In [2]:
rmse

NameError: name 'rmse' is not defined

In [34]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, housing_num, housing_labels, scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

In [35]:
rmse_scores

array([2.96636183, 2.75375911, 4.38018789, 2.61686079, 3.43760627,
       2.80323571, 4.82972174, 3.35588556, 3.20898902, 3.30973743])

In [36]:
def print_scores(scores):
    print("Scores:", scores)
    print("Mean: ", scores.mean())
    print("Standard deviation: ", scores.std())

In [37]:
print_scores(rmse_scores)

Scores: [2.96636183 2.75375911 4.38018789 2.61686079 3.43760627 2.80323571
 4.82972174 3.35588556 3.20898902 3.30973743]
Mean:  3.366234535764588
Standard deviation:  0.6794533336468439


In [38]:
from joblib import dump, load
dump(model, 'Dragon.joblib') 

['Dragon.joblib']

In [39]:
X_test = ts_set.drop("MEDV", axis=1)
Y_test = ts_set["MEDV"].copy()
X_test_prepared = my_pipeline.transform(X_test)
final_predictions = model.predict(X_test_prepared)
final_mse = mean_squared_error(Y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
print(final_predictions, list(Y_test))

[24.372 11.267 26.007 22.008 18.387 15.11  19.999 14.286 31.826 42.235
 19.436 11.708 24.127 27.194 19.649 11.032 31.725 14.317 23.432 18.569
 20.169 18.747 17.951 22.111 18.922 31.329 16.006 32.861  8.553 33.381
 23.973 21.298 23.031 11.07  21.679 11.207 43.891 24.449 23.297 42.218
 24.193 29.606 20.477 20.886 19.099 33.504 44.513 20.262 19.961 21.356
 21.519 15.265 21.109 15.218 25.267 33.466 42.241 28.576 19.694 21.047
 48.037  9.647 18.824 25.064 15.143 33.305 20.1   17.587 19.274 33.552
 25.479 22.691 21.996 22.557 34.343 12.494 15.91  20.098 20.716 21.449
 22.612 21.066 14.622 22.959 20.545 21.189 13.842 21.296 21.391 23.606
 18.552 27.395  6.856 26.791 18.335 29.773 19.982 31.311 14.335 26.672
 21.187 20.282] [16.5, 10.2, 30.1, 23.0, 14.4, 15.6, 19.4, 14.1, 30.3, 35.2, 23.1, 13.8, 25.0, 27.9, 19.5, 12.3, 32.2, 13.5, 23.8, 21.7, 19.2, 19.5, 10.4, 23.2, 18.6, 28.5, 15.2, 32.0, 7.2, 34.6, 20.1, 20.6, 23.6, 13.1, 23.8, 12.7, 43.1, 24.7, 22.2, 44.0, 28.1, 31.0, 21.7, 23.4, 19.5, 33.1

In [40]:
final_rmse

2.9284124404818077

In [41]:
prepared_data = my_pipeline.transform(some_data)

In [42]:
prepared_data[0]

array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23979304, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])

In [43]:
model.predict([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23979304, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])

array([22.389])

In [44]:
from joblib import dump, load
import numpy as np
model = load('Dragon.joblib') 
features = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23979304, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(features)

array([22.389])